targets:  
  $default:  
    builders:  
      injectable_generator:injectable_builder:  
        options:  
          auto_register: true  
          # auto registers any class with a name matches the given pattern  
          class_name_pattern:  
            "DataSource$|Repository$"  
            
          file_name_pattern: "_data_source$|_repository$"