// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7Fh9p6LeW2QsftnA5TsfZOxpuefM-T-M',
    appId: '1:772106314988:web:a44b8a899fd6a5df98f1c9',
    messagingSenderId: '772106314988',
    projectId: 'take-me-there-app',
    authDomain: 'take-me-there-app.firebaseapp.com',
    storageBucket: 'take-me-there-app.appspot.com',
    measurementId: 'G-N1QXC0EQ8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrQ77yYjMBMr-DPZ2fA4a_CEI6n0ODdaM',
    appId: '1:772106314988:android:ba802e987e6fd17998f1c9',
    messagingSenderId: '772106314988',
    projectId: 'take-me-there-app',
    storageBucket: 'take-me-there-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuEEbHI-myPpVvp266asfBxaEQdpL6M-c',
    appId: '1:772106314988:ios:0e70cdc1d7316e5f98f1c9',
    messagingSenderId: '772106314988',
    projectId: 'take-me-there-app',
    storageBucket: 'take-me-there-app.appspot.com',
    iosBundleId: 'com.example.takeMeThereApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuEEbHI-myPpVvp266asfBxaEQdpL6M-c',
    appId: '1:772106314988:ios:4c7c265bcf3f352298f1c9',
    messagingSenderId: '772106314988',
    projectId: 'take-me-there-app',
    storageBucket: 'take-me-there-app.appspot.com',
    iosBundleId: 'com.example.takeMeThereApp.RunnerTests',
  );
}
